bot/urls.py
from django.urls import path

from . import views, fb_views, views2

urlpatterns = [
    path('', views.index, name='index'),
    path('pricing', views.pricing, name='pricing'),
    path('templates', views.templates, name='templates'),
    path('solutions', views.solutions, name='solutions'),
    path('chat/<secret_key>/<lang>/<u_id>/', views.room, name='room'),
    path('chat_customer/<secret_key>/<u_id>/<ques>/', views.room_customer, name='room_customer'),
    path('create_file', views.create_file, name='create_file'),
    path('notify/<id>/<slug>/', views.add_question, name='notify'),
    path('question_list/', views.question_list, name='question_list'),
    path('question_detail/', views.question_detail, name='question_detail'),
    path('chat_history', views.chat_history, name='chat_history'),
    path('get_conversation/<secret_key>/<id>/', views.get_conversation, name='get_conversation'),
    path('remove_note', views.remove_note, name='remove_note'),
    path('remove_emp_notification', views.remove_emp_notification, name='remove_emp_notification'),
    path('change_read_status_note', views.change_read_status_note, name='change_read_status_note'),
    path('change_emp_read_status_note', views.change_emp_read_status_note, name='change_emp_read_status_note'),
    path('login', views.user_login, name='user_login'),
    path('logout', views.user_logout, name='user_logout'),
    path('employee_page/<secret_key>/', views.employee_page, name='employee_page'),
    path('create_user/', views.create_user, name='create_user'),
    path('save_chat_customer', views.save_chat_customer, name='save_chat_customer'),
    path('train_chat_data', views.train_chat_data, name='train_chat_data'),
    path('create_chat_map/<pk>/<bot_slug>/', views.create_chat_map, name='create_chat_map'),
    path('get_user_detail/<secret_key>/', views.get_user_detail, name='get_user_detail'),
    path('update_bot_detail/<pk>/<slug>', views.update_bot_detail, name='update_bot_detail'),
    path('chat_maps/<pk>/<slug>/', views.chat_maps, name='chat_maps'),
    path('bot_list/', views.bot_list, name='bot_list'),
    path('add_bot/', views.add_bot, name='add_bot'),
    path('add_bot_to_user/', views.add_bot_to_user, name='add_bot_to_user'),
    path('delete_chat_title/<id>/', views.delete_chat_title, name='delete_chat_title'),
    path('create_time_slot/', views.create_time_slot, name='create_time_slot'),
    path('provider_detail/', views.provider_detail, name='provider_detail'),
    path('create_service_provider/', views.create_service_provider, name='create_service_provider'),
    path('change_provider_state', views.change_provider_state, name='change_provider_state'),
    path('change_password', views.change_password, name='change_password'),
    path('company_list', views.company_list, name='company_list'),
    path('forget_password', views.forget_password, name='forget_password'),
    path('choose_service_provider/', views.choose_service_provider, name='choose_service_provider'),
    path('integration/', views.facebook_detail, name='facebook_detail'),
    path('change_chat_map_status/<id>', views.change_chat_map_status, name='change_chat_map_status'),
    path('get_slot_list', views.get_slot_list, name='get_slot_list'),
    path('intro_change_language', views.intro_change_language, name='intro_change_language'),
    path('78265fc81d199e51016ef810f1d355e5ea7bef7f682b855d94', fb_views.fb_chat_view, name='fb_chat_view'),
    path('room_test/<pk>/<lang>/', fb_views.room_test, name='room_test'),
    path('create_subscription_plan/', fb_views.create_subscription_plan, name='create_subscription_plan'),
    path('activate_bot/<id>/<secret_key>/', fb_views.activate_bot, name='activate_bot'),
    path('process_payment/<subscription_id>/<subscription_type>', fb_views.process_payment, name='process_payment'),
    path('process-payment/', fb_views.process_payment, name='process_payment'),
    path('payment-done/', fb_views.payment_done, name='payment_done'),
    path('payment-cancelled/', fb_views.payment_canceled, name='payment_cancelled'),
    path('activate_user/<user_pk>', fb_views.activate_user, name='activate_user'),
    path('subscription_list/', fb_views.subscription_list, name='subscription_list'),
    path('faq_page/', fb_views.faq_page, name='faq_page'),
    path('check_ml_status/', fb_views.check_ml_status, name='check_ml_status'),
    path('activate_subscription_plan/<pk>', fb_views.activate_subscription_plan, name='activate_subscription_plan'),
    path('delete_subscription_plan/<pk>', fb_views.delete_subscription_plan, name='delete_subscription_plan'),
    path('get_bot_reply_updated/', views2.get_bot_reply_updated, name='get_bot_reply_updated'),
    path('chat_map_questions/<pk>/<slug>/', views2.chat_map_questions, name='chat_map_questions'),
    path('save_chat_questions/<pk>/<slug>/', views2.save_chat_questions, name='save_chat_questions'),
    path('edit_chat_questions/<pk>/', views2.edit_chat_questions, name='edit_chat_questions'),
    path('remove_save_question/<title_pk>/<question_pk>/', views2.remove_save_question, name='remove_save_question'),
    path('sort_title_questions/<title_pk>/', views2.sort_title_questions, name='sort_title_questions'),
    path('bot_testing/<secret_key>/<lang>/', views2.bot_testing, name='bot_testing'),
    path('get_next_question/<title_pk>/<question_pk>/<is_option>/', views2.get_next_question, name='get_next_question'),
    path('book_selected_slot', views2.book_selected_slot, name='book_selected_slot'),
    path('get_provider_category', views2.get_provider_category, name='get_provider_category'),
    path('get_available_employees/<company_pk>', views2.get_available_employees, name='get_available_employees'),
    path('leave_human_chat', views2.leave_human_chat, name='leave_human_chat'),
    path('check_previous_chat', views2.check_previous_chat, name='check_previous_chat'),
]

chatbot/urls.py
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bot.urls')),
    path('api/', include('bot_api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bot/models.py
from django.db import models
from jsonfield import JSONField
from django.contrib.auth.models import AbstractUser
import uuid
import googletrans
from django.utils.text import slugify


LANGUAGES = ((i, j) for i,j in googletrans.LANGUAGES.items())


def company_image_upload_path(instance, filename):
    return "{company_name}/company_image/{file}".format(company_name=instance.name, file=filename)


def company_question_upload_path(instance, filename):
    return "{company_name}/question_image/{file}".format(company_name=instance.chat_title.chat_title.company.name, file=filename)


class ParentCompany(models.Model):
    name = models.CharField(max_length=30)
    secret_key = models.UUIDField(default=uuid.uuid4, editable=False)

    def __str__(self):
        return self.name


class Company(models.Model):
    parent_company = models.ForeignKey(ParentCompany, on_delete=models.CASCADE, related_name='companies', null=True)
    name = models.CharField(max_length=30)
    secret_key = models.UUIDField(default=uuid.uuid4, editable=False)
    bot_name = models.CharField(max_length=30, default='Talking Bot')
    image = models.ImageField(null=True, blank=True, upload_to=company_image_upload_path)
    color = models.CharField(max_length=10, default='#01578a')
    ques_color = models.CharField(max_length=10, default='#b0eef3')
    intro_ques = models.CharField(max_length=255, default='What help do you need')
    bot_ques = models.CharField(max_length=255, default='Hi! you can ask anything')
    bot_title = models.CharField(max_length=30, default='Talk to bot')
    head_text_color = models.CharField(max_length=10, default='#ffffff')
    intro_text_login = models.CharField(max_length=300, default='Please fill form to continue.')
    bot_introduction = models.CharField(max_length=300, default='Always in your service')
    service_provider = models.CharField(max_length=20, default='service provider')
    language = models.CharField(max_length=15, choices=LANGUAGES, default='en')
    active = models.BooleanField(default=False)
    provider_line = models.CharField(max_length=500, default='Please select the service provider')
    slot_line = models.CharField(max_length=500, default='Please select the slot')
    backup_line = models.CharField(max_length=500, default='I am sorry! I cannot answer this. Would you like to talk to our support?')
    active_date = models.DateTimeField(null=True)
    slug = models.SlugField()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Company, self).save(*args, **kwargs)


class FacebookBotDetails(models.Model):
    company = models.OneToOneField(Company, on_delete=models.CASCADE, related_name='facebook_bot')
    access_key = models.CharField(max_length=255, null=True, blank=True)
    verify_key = models.CharField(max_length=8, unique=True)
    page_id = models.CharField(max_length=30, null=True, blank=True, unique=True)


class User(AbstractUser):
    ROLE = (
        ('admin', 'admin'),
        ('employee', 'employee')
    )
    company = models.ForeignKey(ParentCompany, on_delete=models.CASCADE, related_name='company_name', null=True)
    role = models.CharField(max_length=10, choices=ROLE, default='admin')
    bots = models.ManyToManyField(Company, related_name='users', blank=True)
    available = models.BooleanField(default=False)
    logged_in = models.BooleanField(default=False)

    def __str__(self):
        return self.username


class QuestionTag(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE,
                                related_name='company_tag', default='1')
    tag = models.TextField()


class Question(models.Model):
    question_tag = models.OneToOneField(QuestionTag, on_delete=models.CASCADE,
                                     related_name='question_tag_name')
    question_text = JSONField()
    if_trained = models.BooleanField(default=False)


class Answer(models.Model):
    question_tag = models.OneToOneField(QuestionTag, on_delete=models.CASCADE,
                                     related_name='answer_tag_name')
    question = models.OneToOneField(Question, on_delete=models.CASCADE,
                                 related_name='question_name')
    answer_text = models.TextField()
    customer_care = models.ForeignKey(User, on_delete=models.SET_NULL,
                                      related_name='user_name', null=True)


class Customer(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='company_customer')
    name = models.CharField(max_length=30)
    email = models.EmailField()
    u_field = models.UUIDField(default=uuid.uuid4, editable=False)

    def __str__(self):
        return self.name


class Notification(models.Model):
    TYPE = (
        ('note_no', 'note_no'),
        ('note_yes', 'note_yes'),
    )
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='cust_notify')
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='comp_notify')
    message = models.TextField()
    read_status = models.BooleanField(default=False)
    time_added = models.DateTimeField(auto_now_add=True)
    note_type = models.CharField(max_length=30, choices=TYPE)

    class Meta:
        ordering = ['-pk']


class ChatHistory(models.Model):
    TYPE = (
        ('bot_chat', 'bot_chat'),
        ('user_chat', 'user_chat')
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='company_chat')
    conversation = JSONField(default={'a': 'a'})
    customer = models.ForeignKey(Customer, on_delete=models.DO_NOTHING, related_name='customer_chat')
    date_time = models.DateTimeField(auto_now_add=True)
    date = models.DateField(auto_now_add=True)
    chat_type = models.CharField(max_length=10, choices=TYPE)
    talker = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='user_chat', null=True)
    saved_status = models.BooleanField(default=False)
    trained_status = models.BooleanField(default=True)

    class Meta:
        ordering = ['-pk']


class Conversation(models.Model):
    history = models.ForeignKey(ChatHistory, on_delete=models.CASCADE, related_name='chat_history')
    question = models.TextField(null=True)
    answer = models.TextField(null=True)
    time = models.TimeField(auto_now_add=True)


class NotifyNumber(models.Model):
    TYPE = (
        ('note_no', 'note_no'),
        ('note_yes', 'note_yes'),
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='company_not_number')
    number = models.IntegerField(default=0)
    note_type = models.CharField(max_length=30, choices=TYPE)


class EmpNotification(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='cust_emp_notify')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_emp_notify')
    message = models.TextField()
    read_status = models.BooleanField(default=False)
    time_added = models.DateTimeField(auto_now_add=True)


class EmpNotifyNumber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_not_number')
    number = models.IntegerField(default=0)


class ChatTitle(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='company_chat_title')
    title = models.CharField(max_length=50)
    active = models.BooleanField(default=False)
    slug = models.SlugField()

    class Meta:
        unique_together = ('company', 'title')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(ChatTitle, self).save(*args, **kwargs)


class SurveyQuestion(models.Model):
    TYPE = (
        ('S', 'Single'),
        ('C', 'Carousel'),
    )
    ANS_TYPE = (
        ('I', 'Information'),
        ('O', 'Option'),
        ('T', 'Text'),
    )
    type = models.CharField(max_length=1, choices=TYPE)
    ans_type = models.CharField(max_length=1, choices=ANS_TYPE)
    chat_title = models.ForeignKey('bot.ChatTitle', on_delete=models.CASCADE, related_name='questions')
    question = models.TextField()
    image = models.ImageField(upload_to='images/questions', null=True, blank=True)
    prt_option = models.ForeignKey('bot.SurveyOptions', on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name='child_question')
    prt_question = models.ForeignKey('bot.SurveyQuestion', on_delete=models.SET_NULL, null=True, blank=True,
                                     related_name='child_question')
    url = models.URLField(null=True, blank=True)
    question_form_type = models.CharField(max_length=40, null=True, blank=True)
    number = models.IntegerField(default=1)

    def __str__(self):
        return str(self.number) + ': ' + self.question


class SurveyOptions(models.Model):
    question = models.ForeignKey('bot.SurveyQuestion', on_delete=models.CASCADE, related_name='options')
    option = models.CharField(max_length=50, null=True, blank=True)
    image = models.ImageField(upload_to='images/options', null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)

    def __str__(self):
        if self.option:
            return self.option + ': '+self.question.question[:50]
        else:
            return self.question.question[:50]


class ProviderCategory(models.Model):
    company = models.ForeignKey('bot.Company', on_delete=models.CASCADE, related_name='provider_categories')
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class ServiceProvider(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='user_provider')
    name = models.CharField(max_length=50)

templates/bot/404_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/bot/chat_map_questions.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Questions in Chat map {% endblock %}
{% block style %}
<style>

</style>
{% endblock %}
{% block content %}
<div class="form-collection">
    {% include 'question-template/question-collection.html' %}
</div>
<div class="page-heading">
    <div class="d-flex">
        <div>
            <h2 class="">Questions in Chat Map: {{ chat_title.title }}</h2>
        </div>
        <div class="ml-auto">
            <a href="{% url 'chat_maps' pk=company.pk slug=company.slug %}" class="btn button-submit">Back</a>
        </div>
    </div>
    {% if chat_title.questions.count == 0 %}
    <p class="chat-title-created text-danger font-12">Select question to start creating your chatmap.</p>
    {% endif %}
</div>
<div class="row">
    <div class="col-sm-8">
    <div class="instruction-box mb-3">
            <button class="btn button-submit-blank show-booking-instruction d-none">Show Notice</button>
            <div class="booking-instruction alert alert-info" role="alert">
                <div class="row">
                    <div class="col-sm-9">
                <p class="mb-2 color-94 font-14">Note: If you want to add book appointment in chat map, follow these steps</p>
                <ul class="color-94 font-14">
                    <li>Select "Text Question with Option"</li>
                    <li>Enter "Do you want to book appointment?"</li>
                    <li>Put "Yes" in first option and "No" in second option.</li>
                </ul>
                    </div>
                    <div class="col-sm-3 text-right">
                        <span class="cursor-pointer close-booking-instruction">X</span>
                    </div>
                </div>
            </div>
    </div>
    </div>
</div>
{% if repeat_parent %}
<div class="alert alert-danger" role="alert">
    <p class="mb-0">Following questions have been selected as parent for more than 1  question:
    {% for i in repeat_parent %}
    <span><b>{{ i.number }}</b></span>(<span>
    {% for j in i.child_question.all %}
        {{ j.number }}{% if not forloop.last %},{% endif %}
    {% endfor %}
    </span>)
    {% if not forloop.last %},{% endif %}
        {% endfor %}</p>
</div>
{% endif %}
{% if repeat_option %}
<div class="alert alert-danger" role="alert">
<p class="mb-0">Repeated parent options:
{% for i in repeat_option %}
<span><b>{{ i.question.number }}-{{ i.option }}</b></span>(<span>
{% for j in i.child_question.all %}
    {{ j.number }}{% if not forloop.last %},{% endif %}
{% endfor %}
</span>)
{% if not forloop.last %},{% endif %}
    {% endfor %}
</p>
</div>
{% endif %}

<div class="questions-list w-75 pl-3 pr-4">
    <div class="saved_questions">
        {% include 'question-template/map_question.html' %}
    </div>
    <div class="new_question">

    </div>
</div>
{% if questions.count > 1 %}
<div class="mt-4 order-question-container d-none position-fixed" style="bottom: 20px;">
    <button class="sort-question btn bg-orange text-white">Update Question Order</button>
    <p class="btn-error d-none font-12 text-danger">No new changes in question sequence.</p>
</div>
{% endif %}
<div class="question-option-container">
    <div class="add-question-instruction">
        <p class="instruction-heading">Select Question</p>
        <p class="instruction-text">Select The Type Of The Question To Add The Template To The Map And Customize It.</p>
    </div>
    <div class="question-type-container">
            <div class="question-type-list" data-form="instruction-question" data-ans-type="I" data-type="S">
                <p class="question-type-text">Instruction</p>
                <p class="question-type-description"></p>
            </div>
            <div class="question-type-list" data-form="text-question" data-ans-type="T" data-type="S">
                <p class="question-type-text">
                    Text Question
                </p>
                <p class="question-type-description">
                    Single text question (Image and URL is optional)
                </p>
            </div>
            <div class="question-type-list" data-form="text-option-question" data-ans-type="O" data-type="S">
                <p class="question-type-text">
                    Text Question with Option
                </p>
                <p class="question-type-description">

                </p>
            </div>
            <div class="question-type-list" data-form="carousel-question" data-ans-type="T" data-type="C">
                <p class="question-type-text">
                    Image Carousel
                </p>
                <p class="question-type-description">

                </p>
            </div>
            <div class="question-type-list" data-form="carousel-option-question" data-ans-type="O" data-type="C">
                <p class="question-type-text">
                    Image Carousel with Option
                </p>
                <p class="question-type-description">

                </p>
            </div>
        </div>
</div>
<div class="modal fade" id="removeQuestionModal" tabindex="-1" role="dialog" aria-labelledby="removeQuestionModalLabel"
     aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="removeQuestionModalLabel">Remove Question</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p class="mb-0">Are you sure you want to delete this question?</p>
          <p class="delete-question bold"><b></b></p>
      </div>
      <div class="modal-footer">
        <a href="#" type="button" class="btn bg-orange text-white">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block script %}
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
$(document).ready(function(){
<!--    $( ".sortable" ).sortable({-->
<!--      placeholder: "ui-state-highlight",-->
<!--      stop: function(event, ui){-->
<!--        $(".order-question-container").removeClass("d-none")-->
<!--      }-->
<!--    });-->
<!--    $( ".sortable" ).disableSelection();-->

    // sort questions
    $(".sort-question").click(function(){
    var l_sort = [];
    $(".card").each(function(){
        l_sort.push($(this).attr("id"))
    })
    if(l_sort.length > 0){
        page_url = "{% url 'sort_title_questions' title_pk=chat_title.pk %}"
        SortQuestions(l_sort, page_url)
    }
    else{
        $(this).siblings("p.btn-error").removeClass("d-none")
    }
    })

    // Select parent question
    $(document).on("change", ".question-select", function(){
    selected_question = $(this).find("option:selected").val()
    option_select = $(this).parent().parent().parent().find(".parent-options")
    option_select.find("option").each(function(){
        if($(this).attr("data-parent") != selected_question){
            $(this).addClass("d-none")
        }
        else{
            $(this).removeClass("d-none")
        }
    })
    })
    // Remove unsaved form
    $(document).on("click", ".remove-this-form", function(){
    $(this).parent().parent().remove();
    })

    // Open and Close Booking Instruction
    $(".close-booking-instruction").click(function(){
        $(".booking-instruction").addClass("d-none")
        $(".show-booking-instruction").removeClass("d-none")
    });
    $(".show-booking-instruction").click(function(){
        $(".show-booking-instruction").addClass("d-none")
        $(".booking-instruction").removeClass("d-none")
    });

    //  Add Question
    $(".question-type-list").click(function(){
        ques_form = $(this).attr("data-form")
        data_type = $(this).attr("data-type")
        data_ans_type = $(this).attr("data-ans-type")
        form_clone = $(".form-collection").find("#"+ques_form).clone(true)
        form_clone.removeClass("d-none")
        form_clone.find("#id_type").val(data_type)
        form_clone.find("#id_ans_type").val(data_ans_type)
        $(".questions-list").find(".new_question").append(form_clone)
    })

    // Remove option
    $(document).on("click", ".remove-question-option", function(){
        deleteForm(this, "form", 2, "options")
        return false;
    })

    // Add Option
    $(document).on("click", ".add-it .add-option", function(){
        addForm(this, "form")
        return false;
    })

    // Submit question form edit_chat_questions
    $(document).on("submit", ".create-question-form", function(){
    var $this = $(this)
    $.ajax({
            data: new FormData(this),
            processData: false,
            contentType: false,
            type: 'post',
            url: "{% url 'save_chat_questions' pk=chat_title.pk slug=chat_title.slug %}",
            success: function(data) {
                if(data['status'] == true){
                    location.reload();
                }
                else if(data['status'] == 'form_error'){
                    $this.find(".error-fields").html("")
                    $.each(data['message'], function(index, element) {
                        $this.find(".error-fields").append("<p class='font-12 text-danger error-question-text'>"+index+ ": "+ element+"</p>")
                    });
                }
                else if(data['status'] == false){
                    $this.find(".error-question-text:first").html(data['message'])
                }
             },
            error: function(data){
               alert("Something went wrong. Please refresh and try again.")
            }
        });
    return false;
    });

    // Submit question form
    $(document).on("submit", ".saved_question_form", function(){
    var $this = $(this)
    var question_pk = $(this).find(".existing_question").val()
    $.ajax({
            data: new FormData(this),
            processData: false,
            contentType: false,
            type: 'post',
            url: "/edit_chat_questions/"+ question_pk +"/",
            success: function(data) {
                if(data['status'] == true){
                    location.reload();
                }
                else if(data['status'] == 'form_error'){
                    $this.find(".error-fields").html("")
                    $.each(data['message'], function(index, element) {
                        $this.find(".error-fields").append("<p class='font-12 text-danger error-question-text'>"+index+ ": "+ element+"</p>")
                    });
                }
                else if(data['status'] == false){
                    $this.find(".error-question-text:first").html(data['message'])
                }
             },
            error: function(data){
               alert("Something went wrong. Please refresh and try again.")
            }
        });
    return false;
    });

    // Remove question modal
    $('#removeQuestionModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget)
      var question = button.data('question')
      var url = button.data('url')
      var modal = $(this)
      modal.find('.delete-question b').text(question)
      modal.find('.modal-footer a').attr("href", url)
    })
});

</script>
{% endblock %}

templates/bot/check_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Not Allowed</title>
</head>
<body>

</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>

$(document).ready(function(){
    alert("You are not allowed to view this page")
    function redirect(){
       window.location.href = "{% url 'user_login' %}";
       return false;
    }

    setTimeout(redirect, 500);
});
</script>
</html>

templates/bot/create_map.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Create Chat Map {% endblock %}
{% block style %}
<style>

</style>
{% endblock %}
{% block content %}
<div class="page-heading">
    <h2 class="float-left">Create Chat Map: {{ company.name }}</h2>
    <a href="{% url 'chat_maps' pk=company.pk slug=company.slug %}" class="btn button-submit float-right">Back</a>
</div>
<div class="clearfix"></div>
<div class="row" style="margin-top: 30px;">
    <div class="col-sm-12">
        <div class="title-div ml-auto mr-auto">
            <form method="post" class="create-title-form mx-auto w-50">
                {% csrf_token %}
                <div class="position-relative">
                {{ title_form.title }}
                <label class="position-absolute form-check-label">Enter title of chat map</label>
                {{ title_form.title.errors.as_text }}
                <button id="save-title" class="btn bg-orange text-white text-uppercase" name="title-form">Create</button>
                </div>

            </form>
            <p class="error-list error-chat-name hidden-element">This is an error.</p>
        </div>
    </div>
</div>

{% endblock %}


{% block script %}

{% endblock %}

templates/bot/employee_home.html
{% extends 'base_employee.html' %}

templates/bot/provider-list.html
{% load static %}

{% for provider in service_providers %}
<div class="provider-detail" data-pk="{{ provider.pk }}">
    <img src="{% static 'page-icons/smile.png' %}">
    <p>{{ provider.name }} ({{ provider.company.name }}{% if provider.category %}/{{ provider.category.name }}{% endif %})</p>
</div>
{% empty %}
<p style="font-size: 14px;">
    No Service providers has been added..
</p>
{% endfor %}

templates/bot/question_detail.html
{% if form %}
<div class="add-question-container" style="position: relative;">
<form method="post" id="edit-question-form" style="position: fixed;">
    {% csrf_token %}
    <input id="edited-question-pk" name="question-pk" hidden>
    <table class="add-question">

        <tr>
            <td><p style="margin-bottom: 5px; font-weight: 700">Question</p>
                {{ form.question }}
            </td>
        </tr>
        <tr>
            <td><p style="margin-bottom: 5px; font-weight: 700">Answer</p>
                {{ form.answer }}
            </td>
        </tr>
    </table>
    <input type="submit" value="submit" class="btn button-submit ml-auto" name="edit-question-submit">
</form>
</div>
{% else %}
<div class="ml-auto mr-auto" style="height: max-content; margin-top:50%;width: max-content;">
<p class="">Click on Edit button to edit the question.</p>
</div>
{% endif %}