bot/urls.py
from django.urls import path

from . import views, fb_views, views2

urlpatterns = [
    path('', views.index, name='index'),
    path('pricing', views.pricing, name='pricing'),
    path('templates', views.templates, name='templates'),
    path('solutions', views.solutions, name='solutions'),
    path('chat/<secret_key>/<lang>/<u_id>/', views.room, name='room'),
    path('chat_customer/<secret_key>/<u_id>/<ques>/', views.room_customer, name='room_customer'),
    path('create_file', views.create_file, name='create_file'),
    path('notify/<id>/<slug>/', views.add_question, name='notify'),
    path('question_list/', views.question_list, name='question_list'),
    path('question_detail/', views.question_detail, name='question_detail'),
    path('chat_history', views.chat_history, name='chat_history'),
    path('get_conversation/<secret_key>/<id>/', views.get_conversation, name='get_conversation'),
    path('remove_note', views.remove_note, name='remove_note'),
    path('remove_emp_notification', views.remove_emp_notification, name='remove_emp_notification'),
    path('change_read_status_note', views.change_read_status_note, name='change_read_status_note'),
    path('change_emp_read_status_note', views.change_emp_read_status_note, name='change_emp_read_status_note'),
    path('login', views.user_login, name='user_login'),
    path('logout', views.user_logout, name='user_logout'),
    path('employee_page/<secret_key>/', views.employee_page, name='employee_page'),
    path('create_user/', views.create_user, name='create_user'),
    path('save_chat_customer', views.save_chat_customer, name='save_chat_customer'),
    path('train_chat_data', views.train_chat_data, name='train_chat_data'),
    path('create_chat_map/<pk>/<bot_slug>/', views.create_chat_map, name='create_chat_map'),
    path('get_user_detail/<secret_key>/', views.get_user_detail, name='get_user_detail'),
    path('update_bot_detail/<pk>/<slug>', views.update_bot_detail, name='update_bot_detail'),
    path('chat_maps/<pk>/<slug>/', views.chat_maps, name='chat_maps'),
    path('bot_list/', views.bot_list, name='bot_list'),
    path('add_bot/', views.add_bot, name='add_bot'),
    path('add_bot_to_user/', views.add_bot_to_user, name='add_bot_to_user'),
    path('delete_chat_title/<id>/', views.delete_chat_title, name='delete_chat_title'),
    path('create_time_slot/', views.create_time_slot, name='create_time_slot'),
    path('provider_detail/', views.provider_detail, name='provider_detail'),
    path('create_service_provider/', views.create_service_provider, name='create_service_provider'),
    path('change_provider_state', views.change_provider_state, name='change_provider_state'),
    path('change_password', views.change_password, name='change_password'),
    path('company_list', views.company_list, name='company_list'),
    path('forget_password', views.forget_password, name='forget_password'),
    path('choose_service_provider/', views.choose_service_provider, name='choose_service_provider'),
    path('integration/', views.facebook_detail, name='facebook_detail'),
    path('change_chat_map_status/<id>', views.change_chat_map_status, name='change_chat_map_status'),
    path('get_slot_list', views.get_slot_list, name='get_slot_list'),
    path('intro_change_language', views.intro_change_language, name='intro_change_language'),
    path('78265fc81d199e51016ef810f1d355e5ea7bef7f682b855d94', fb_views.fb_chat_view, name='fb_chat_view'),
    path('room_test/<pk>/<lang>/', fb_views.room_test, name='room_test'),
    path('create_subscription_plan/', fb_views.create_subscription_plan, name='create_subscription_plan'),
    path('activate_bot/<id>/<secret_key>/', fb_views.activate_bot, name='activate_bot'),
    path('process_payment/<subscription_id>/<subscription_type>', fb_views.process_payment, name='process_payment'),
    path('process-payment/', fb_views.process_payment, name='process_payment'),
    path('payment-done/', fb_views.payment_done, name='payment_done'),
    path('payment-cancelled/', fb_views.payment_canceled, name='payment_cancelled'),
    path('activate_user/<user_pk>', fb_views.activate_user, name='activate_user'),
    path('subscription_list/', fb_views.subscription_list, name='subscription_list'),
    path('faq_page/', fb_views.faq_page, name='faq_page'),
    path('check_ml_status/', fb_views.check_ml_status, name='check_ml_status'),
    path('activate_subscription_plan/<pk>', fb_views.activate_subscription_plan, name='activate_subscription_plan'),
    path('delete_subscription_plan/<pk>', fb_views.delete_subscription_plan, name='delete_subscription_plan'),
    path('get_bot_reply_updated/', views2.get_bot_reply_updated, name='get_bot_reply_updated'),
    path('chat_map_questions/<pk>/<slug>/', views2.chat_map_questions, name='chat_map_questions'),
    path('save_chat_questions/<pk>/<slug>/', views2.save_chat_questions, name='save_chat_questions'),
    path('edit_chat_questions/<pk>/', views2.edit_chat_questions, name='edit_chat_questions'),
    path('remove_save_question/<title_pk>/<question_pk>/', views2.remove_save_question, name='remove_save_question'),
    path('sort_title_questions/<title_pk>/', views2.sort_title_questions, name='sort_title_questions'),
    path('bot_testing/<secret_key>/<lang>/', views2.bot_testing, name='bot_testing'),
    path('get_next_question/<title_pk>/<question_pk>/<is_option>/', views2.get_next_question, name='get_next_question'),
    path('book_selected_slot', views2.book_selected_slot, name='book_selected_slot'),
    path('get_provider_category', views2.get_provider_category, name='get_provider_category'),
    path('get_available_employees/<company_pk>', views2.get_available_employees, name='get_available_employees'),
    path('leave_human_chat', views2.leave_human_chat, name='leave_human_chat'),
    path('check_previous_chat', views2.check_previous_chat, name='check_previous_chat'),
]

chatbot/urls.py
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bot.urls')),
    path('api/', include('bot_api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bot/forms.py
from django import forms
from django.forms import BaseFormSet
from .models import Customer, User, Company, ServiceProvider, TimeSlots, BookedSlots, FacebookBotDetails, ParentCompany
from django.contrib.auth import authenticate
from django.contrib.admin import widgets


class RequiredFormSet(BaseFormSet):
    def __init__(self, *args, **kwargs):
        super(RequiredFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False


class AddQuestionForm(forms.Form):
    tag = forms.CharField(max_length=30, required=False, widget=forms.TextInput({'hidden': 'hidden'}))
    question = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Enter Question', 'class': 'form-text-area'}))
    answer = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Enter Answer', 'class': 'form-text-area'}))

    def clean_question(self):
        question = self.cleaned_data.get('question')

        if question == "":
            raise forms.ValidationError('This field is required.')

        return question

    def clean_answer(self):
        answer = self.cleaned_data.get('answer')

        if answer == "":
            raise forms.ValidationError('This field is required.')

        return answer


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('name', 'email')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control popup-form-input',
                                           'placeholder': 'name *'}),
            'email': forms.EmailInput(attrs={'class': 'form-control popup-form-input',
                                             'placeholder': 'email *'}),
        }


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=30,
                               widget=forms.TextInput(attrs={'class': 'login-input', 'id': 'inputEmail'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'login-input'}))

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if username == "":
            raise forms.ValidationError('This field is required.')

        return username

    def clean_password(self):
        password = self.cleaned_data.get('password')

        if password == "":
            raise forms.ValidationError('This field is required.')

        return password

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError('Username or Password is incorrect')
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user.is_active:
            return forms.ValidationError('User is not active.')
        return user


class ParentCompanyForm(forms.ModelForm):
    class Meta:
        model = ParentCompany
        fields = ('name', )
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Company Name *'}),
        }


class CreateUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'placeholder': 'Password *'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'placeholder': 'Confirm Password *'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'confirm_password', 'bots')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username *'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email *'}),
            'bots': forms.SelectMultiple(attrs={'class': 'select-bot selectpicker', 'placeholder': 'Select Bot'})
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if not email:
            raise forms.ValidationError(
                "This field is required."
            )
        user = User.objects.filter(email=email).exists()
        if user:
            raise forms.ValidationError(
                "This email has been register."
            )

        return email

    def clean_username(self):
        username = self.cleaned_data.get('username')

        user = User.objects.filter(username=username).exists()
        if user:
            raise forms.ValidationError(
                "This username has been register."
            )

        return username

    def clean(self):
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "Password and Confirm Password does not match"
            )


class AddBotToUser(forms.ModelForm):
    class Meta:
        model = User
        fields = ('bots', )
        widgets = {
            'bots': forms.SelectMultiple(attrs={'class': 'select-bot selectpicker', 'placeholder': 'Select Bot'})
        }


class UpdateBotForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('bot_name', 'image', 'color', 'intro_ques', 'bot_title', 'bot_ques', 'head_text_color',
                  'service_provider', 'intro_text_login')
        widgets = {
            'bot_name': forms.TextInput(attrs={'class': 'form-control'}),
            'color': forms.TextInput(attrs={'class': 'form-control'}),
            'intro_ques': forms.TextInput(attrs={'class': 'form-control'}),
            'bot_title': forms.TextInput(attrs={'class': 'form-control'}),
            'bot_ques': forms.TextInput(attrs={'class': 'form-control'}),
            'head_text_color': forms.TextInput(attrs={'class': 'form-control'}),
            'intro_text_login': forms.TextInput(attrs={'class': 'form-control'}),
            'service_provider': forms.TextInput(attrs={'class': 'form-control'}),
        }


class CreateCompany(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('name', 'language', 'bot_name', 'service_provider', 'image', 'color', 'intro_ques', 'bot_ques', 'bot_title',
                  'head_text_color', 'intro_text_login', 'provider_line', 'slot_line',
                  'ques_color', 'backup_line', 'bot_introduction')
        widgets = {
            'language': forms.Select(attrs={'class': 'selectpicker choose-language', 'data-live-search': 'true'})
        }

    def clean_name(self):
        name = self.cleaned_data['name']
        if not all(x.isalpha() or x.isspace() for x in name):
            return forms.ValidationError("Only letters and space is allowed.")

        return name


class CreateAdmin(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')


class CreateProviderForm(forms.ModelForm):
    class Meta:
        model = ServiceProvider
        fields = ('name', 'category', 'company')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter name of Provider', 'class': 'provider-name'})
        }


class TimeSlotForm(forms.ModelForm):
    DAYS = (
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday'),
        ('All', 'All')
    )
    start = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'HH:MM'}))
    end = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'HH:MM'}))
    provider = forms.CharField(widget=forms.TextInput(attrs={'hidden': 'hidden'}))

    class Meta:
        model = TimeSlots
        fields = ('start', 'end', 'provider')


class ChangePasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'placeholder': 'Password'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                         'placeholder': 'Confirm Password'}))

    def clean(self):
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )


class ForgetPasswordForm(forms.Form):
    username = forms.CharField()

    def clean_username(self):
        username = self.cleaned_data['username']
        user_exist = User.objects.filter(username=username).exists()
        if username == "":
            raise forms.ValidationError('This field is required.')

        if not user_exist:
            raise forms.ValidationError('This username has not been registered. Please contact to admin.')

        user = User.objects.get(username=username)
        email = user.email

        if not email:
            raise forms.ValidationError('Email ID for account with this username has not been provided. Please contact to admin.')

        return username


class FacebookBotDetailForm(forms.ModelForm):
    class Meta:
        model = FacebookBotDetails
        fields = ('access_key', 'page_id')
        widgets = {

templates/question-template/add_bot_to_user.html
<form method="post" id="RegistrationForm">
            {% csrf_token %}
            <input name="user_pk" value="{{ user.pk }}" hidden>
            {{ form.non_field_errors }}
                <div class="form-group">
                <select class="select-bot selectpicker" multiple name="add_bot_to_user">
                        {% for i in company_bots %}
                            {% if i in user.bots.all %}
                    <option value="{{ i.pk }}" selected>{{ i.name }}</option>
                            {% else %}
                        <option value="{{ i.pk }}">{{ i.name }}</option>
                    {% endif %}
                        {% endfor %}
                 </select>
          </div>
                <div class="form-button">
        <button name='add_bot_submit' type="submit" class="btn button-submit ml-auto mr-auto">Submit</button>
                </div>
        </form>

templates/question-template/bot_inactive.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Not Available</title>
    <link rel="stylesheet" type="text/css" href="{% static 'project/bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'user_front/css/styles.css' %}">
    <style>

    html, body{
    height: 100%;
    }
    .intro-div{
    padding: 10px;
    font-size: 14px;
    margin-bottom: 20px;
    background: {{ company.color }};
    color: {{ company.head_text_color }};
    padding-right: 30px;
    }
    .bot-img {
	display: inline-block;
    background-repeat: no-repeat;
    background-position: center center;
    background-size: cover;
    width: 40px;
    height: 40px;
    border-radius: 50%;
	float: left;
	margin-right: 15px;
	}
	{% if not_found %}
    body{
    border: 1px solid #76b61b;
    }
    .intro-div{
    background: #76b61b;
    color: #ffffff;
    }
    {% endif %}
    </style>
</head>
<body class="">
{% if not_found %}
<div class="intro-div">
  {% if company.image %}
			<div class="bot-img" style="background-image: url('{{ company.image.url }}');margin-right:20px;"></div>
			{% endif %}
			<p class="mb-0" id="bot-intro-text">Hi ! I am Bot.</p>
			<p class="mb-0" style="display: none;" id="curr-lang">{{ company.language }}</p>
    <p id="bot-instruction-text" class="mb-0">I am out of service</p>
  </div>
{% else %}
    <div class="intro-div">
  {% if company.image %}
			<div class="bot-img" style="background-image: url('{{ company.image.url }}');margin-right:20px;"></div>
			{% endif %}
			<p class="mb-0" id="bot-intro-text">Hi ! I am {{ company.bot_name|title }}.</p>
			<p style="display: none;" id="curr-lang">{{ company.language }}</p>
    <p id="bot-instruction-text" class="mb-0">I am out of service</p>
  </div>
{% endif %}

    <div class="mt-5">
        <div class="img-container text-center">
            <img src="{% static 'icons/Botlogo.png' %}" class="top-nav-icon" style="width: 50px;">
        </div>
        <div class="text-container">
            <p class="text-center mt-0" style="font-family: lato;">Sorry! I am not available.</p>
        </div>
    </div>


</body>
<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</html>

templates/question-template/carousel.html
{% load static %}
<div class="reply-div w-100" style="min-width:150px;" data-child="{{ question_data.child_id }}" data-number="{{ question_data.number }}">
  <p class="mb-0">{{ question_data.question }}</p>

    <div id="carousel-{{ question_data.pk }}" class="carousel slide mt-2" data-ride="carousel">
      <div class="carousel-inner">
          {% for frame in question_data.detail %}
            <div {% if forloop.counter == 1 %} class="carousel-item active" {% else %} class="carousel-item" {% endif %}>
              {% if frame.text %}
              <p class="mb-2 text-center"><b>{{ frame.text }}</b></p>
              {% endif %}
              {% if frame.image %}
                <img src="{{ frame.image }}" class="img-fluid mb-2">
              {% endif %}

              {% if frame.description %}
                {{ frame.description }}
              {% endif %}
              {% if frame.option %}
                <button class="sent-span btn btn-primary select-option" data-number="{{ frame.number }}"
                        data-title-pk="{{ question_data.title_pk }}" data-child="{{ frame.child_id }}">
                    {{ frame.option }}
                </button>
              {% endif %}
            </div>
          {% endfor %}
      </div>
      <a class="carousel-control-prev" href="#carousel-{{ question_data.pk }}" role="button" data-slide="prev">
        <span class="fa fa-angle-left" aria-hidden="true" style="color: #000;"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-{{ question_data.pk }}" role="button" data-slide="next">
        <span class="fa fa-angle-right" aria-hidden="true" style="color: #000;"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
</div>

templates/question-template/map_question.html
<div class="accordion sortable" id="mapQuestionList">
    {% for question in questions.all %}
  <div class="card ui-state-default" id="{{ question.pk }}">
    <div class="card-header" id="heading{{ question.pk }}">
      <h2 class="mb-0">
        <a class="btn btn-link btn-block text-left collapsed d-flex" type="button" data-toggle="collapse"
                data-target="#collapse{{ question.pk }}" aria-expanded="true" aria-controls="collapse{{ question.pk }}">
          <div>
            <p class="mb-0"><span class="question-number" data-pk="{{ question.pk }}"><b>{{question.number}}.</b></span> {{question.question}}</p>

          {% if question.prt_option %}
          <p class="mb-0 font-12 ml-2"><b>Parent</b>: {{ question.prt_option.option }} - <span>{{ question.prt_option.question.question }}</span></p>
          {% elif question.prt_question %}
          <p class="mb-0 font-12 ml-2"><b>Parent</b>: {{ question.prt_question.question }}</p>
          {% endif %}
          </div>
          <div class="ml-auto">
            <span class="text-orange font-12 cursor-pointer remove-question" data-target="#removeQuestionModal"
            data-toggle="modal" data-question="{{ question.question }}"
            data-url="{% url 'remove_save_question' title_pk=question.chat_title.pk question_pk=question.pk %}">Remove</span>
          </div>
        </a>
      </h2>
    </div>

    <div id="collapse{{ question.pk }}" class="collapse" aria-labelledby="heading{{ question.pk }}"
         data-parent="#mapQuestionList">
      <div class="card-body">
        <form method="post" enctype="multipart/form-data" class="saved_question_form">
          {% csrf_token %}
          <input type="text" name="type" hidden value="{{ question.type }}" required id="id_type">
          <input type="text" name="ans_type" hidden value="{{ question.ans_type }}" required id="id_ans_type">
          <input type="hidden" name="existing_pk" value="{{ question.pk }}" class="existing_question">
          <input type="hidden" value="{{ question.question_form_type }}" name="question_form_type">
          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <label>Text <span class="text-danger">*</span></label>
                <textarea name="question" cols="40" rows="3" class="form-control" required="" id="id_question">
                  {{ question.question }}
                </textarea>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-3">
              <div class="form-group">
                <label>Parent Question</label>
                <select name="prt_question" class="form-control question-select" id="id_prt_question">
                  <option value="" selected="">---------</option>
                  {% for i in chat_title.questions.all %}
                    {% if question.prt_question and question.prt_question.pk == i.pk %}
                    <option value="{{ i.pk }}" selected>{{i.number}}: {{ i.question }}</option>
                    {% elif question.prt_option and question.prt_option.question.pk == i.pk %}
                    <option value="{{ i.pk }}" selected>{{i.number}}: {{ i.question }}</option>
                    {% else %}
                    <option value="{{ i.pk }}">{{i.number}}: {{ i.question }}</option>
                    {% endif %}
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="col-sm-3">
              <div class="form-group">
                <label>Parent Option</label>
                <select name="prt_option" class="form-control parent-options" id="id_prt_option">
                  <option value="" selected="">---------</option>
                  {% for i in chat_title.questions.all %}
                    {% for j in i.options.all %}
                      {% if j.option %}
                        {% if question.prt_option %}
                          {% if question.prt_option.pk == j.pk %}
                            <option value="{{j.pk}}" data-parent="{{ i.pk }}" selected>{{j}}</option>
                          {% elif question.prt_option.question.pk == i.pk %}
                            <option value="{{j.pk}}" data-parent="{{ i.pk }}">{{j}}</option>
                          {% else %}
                            <option value="{{j.pk}}" data-parent="{{ i.pk }}" class="d-none">{{j}}</option>
                          {% endif %}
                        {% else %}
                          <option value="{{j.pk}}" data-parent="{{ i.pk }}">{{j}}</option>
                        {% endif %}
                      {% endif %}
                    {% endfor %}
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="col-sm-3">
              <div class="form-group">
                <label>URL</label>
                <input type="url" name="url" {% if question.url %}value="{{ question.url }}"{% endif %} class="form-control" maxlength="200" id="id_url">
              </div>
            </div>
            <div class="col-sm-3">
              <div class="form-group">
                <label>Image</label>
                <input type="file" name="image" accept="image/*" id="id_image">
                {% if question.image %}
                <a href="{{ question.image.url }}" target="_blank" class="font-12 text-orange">Current Image</a>
                {% endif %}
              </div>
            </div>
          </div>

          {% if question.options.count %}

          <div class="test">
            <input type="hidden" name="form-TOTAL_FORMS" value="{{ question.options.count }}" id="id_form-TOTAL_FORMS">
            <input type="hidden" name="form-INITIAL_FORMS" value="0" id="id_form-INITIAL_FORMS">
            <input type="hidden" name="form-MIN_NUM_FORMS" value="1" id="id_form-MIN_NUM_FORMS">
            <input type="hidden" name="form-MAX_NUM_FORMS" value="1000" id="id_form-MAX_NUM_FORMS">
            {% for i in question.options.all %}
            <div class="item row">
              {% if i.image %}
              <div class="col-sm-2">
                <label>Image <span class="text-danger">*</span></label>
                <input type="file" name="form-{{ forloop.counter0 }}-image" accept="image/*" id="id_form-{{ forloop.counter0 }}-image">
                <a href="{{ i.image.url }}" target="_blank" class="text-orange font-12">Current Image</a>
              </div>
              {% endif %}
              {% if i.option %}
              <div class="col-sm-3">
                <label>Option <span class="text-danger">*</span></label>
                <input type="text" name="form-{{ forloop.counter0 }}-option" class="form-control" maxlength="30"
                       value="{{ i.option }}" id="id_form-{{ forloop.counter0 }}-option">
              </div>
              {% endif %}
              <div class="col-sm-3">
                <label>URL</label>
                <input type="url" name="form-{{ forloop.counter0 }}-url" class="form-control" maxlength="200"
                       id="id_form-{{ forloop.counter0 }}-url" {% if i.url %}value="{{ i.url }}"{% endif %}>
              </div>
              <div class="col-sm-3">
                <label>Text</label>
                <textarea name="form-{{ forloop.counter0 }}-text" cols="40" rows="2" class="form-control"
                          id="id_form-{{ forloop.counter0 }}-text">
                  {% if i.text %}{{ i.text }}{% endif %}
                </textarea>
              </div>
              <div class="col-sm-1 align-self-center"><span class="remove-question-option">X</span></div>
            </div>
            {% endfor %}

            <div class="add-it">
                <button class="add-option button-submit-blank btn">Add option</button>
            </div>
          </div>

          {% endif %}
          <div class="mt-2 text-right">
            <button type="submit" value="Save" class="btn bg-orange text-white">Save</button>
          </div>
          <div class="error-fields text-right">
            <p class="text-danger font-12 error-question-text"></p>
          </div>
        </form>
      </div>
    </div>
  </div>
    {% endfor %}
</div>

templates/question-template/payment_cancelled.html
{% extends 'base.html' %}
{% block title %}Payment Cancelled{% endblock %}
{% block content %}

<p>Payment cancelled. Click <a href="{% url 'bot_list' %}">here</a> to return.</p>

{% endblock %}

templates/question-template/process_payment.html
{% extends 'base.html' %}

{% block title %}Make Payment{% endblock %}

{% block content %}
<div class="page-heading">
    <h2>Buy Subscription</h2>
</div>
<h4>Plan details</h4>
<p>Name: {{ subscription.name }}</p>
<p>Subscription Type: {{ subscription_type }}</p>
<p>Price: {{ price }}</p>
    <h4>Pay with PayPal</h4>
    {{ form.render }}
{% endblock %}